splunk/attack_range

ansible/vars/vars.yml.default, attack_range.py, terraform/main.tf
cleaned up attackiq/firedrill logic for now as we are not supporting this simulation engine yet!
=> removing firedrill

.attack_range/README.md, attack_range.py
@P4T12ICK please merge in when you get to review
=> adjusted working dir as a hidden one

.attack_range/README.md, ansible/inventory/hosts, ansible/vars/vars.yml, attack_range.py, modules/logger.py
This adds a logging arg/file from the execution of the range. Also gets used to print the messages to console. Corrected some print statements for simulation
=> Adding logging

README.md, ansible/inventory/hosts, ansible/vars/vars.yml, attack_range.py
This feature branch allow to stop and resume the Attack Range using Terraform or Vagrant.
=> Crl 1692 stop and resume mode

ansible/roles/search_head/tasks/install_windows_ta.yml
Small bug fix for ansible file install_windows_ta. Path was still hard-coded.
=> small bug fix

attack_range.py
something I noticed fixing the fact that init message got printed twice
=> minor removal of double logging

attack_range.conf
updated s3 path to make sure CI job catches it
=> updated package path

terraform/main.tf
ADDING 10.0.0.8/32 AS ANOTHER INGRESS RULEE
=> adding ingress rule to accept traffic from target machines

.dependabot/config.yml
automatically merges PRs from dependabot
=> adding automerge to the attack range

vagrant/splunk_server/Vagrantfile
Small fix for Vargrant in attack_range
=> updated mltk variable names

README.md
yeah just adding more flair to the readme
=> adding demo video

ansible/roles/search_head/files/web.conf, ansible/roles/search_head/tasks/configure_inputs.yml, ansible/roles/search_head/tasks/configure_server_conf.yml, ansible/roles/search_head/tasks/configure_web_conf.yml, ansible/roles/search_head/tasks/install_mltk_app.yml, ansible/roles/search_head/tasks/main.yml, ansible/roles/windows_universal_forwarder/files/sysmon_inputs.conf, attack_range.conf, modules/splunk_sdk.py, requirements.txt, vagrant/Vagrantfile, vagrant/windows-domain-controller/Vagrantfile, vagrant/windows-server/Vagrantfile
Updated the Attack Range to Splunk Version 8 and all new versions of TA and Apps. Additionally, fix ed some small issues. Thanks for reviewing.
=> bumped to splunk v8

attack_range.py, modules/VagrantController.py, vagrant/Vagrantfile
missing an import for the vagrant controller, plus updated error messages
=> fixing minor issues with listing machine

terraform/modules/phantom-server/resources.tf
Fixed a bug in ressource.tf for phantom when built with packer.
=> bug fix in ressource.tf for phantom

attack_range.conf
=> bug fix ami issue

attack_range.conf, modules/CustomConfigParser.py
when no domain controller is set, the join flag should be 0, otherwise clients in the range DNS does not work.
=> Fixing empty dc bug

ansible/roles/sysmon/tasks/windows-sysmon.yml
=> fixes an issue introduced by sysmonv11

ansible/roles/search_head/tasks/install_enterprise_security.yml, attack_range.conf
=> small fix for ES

README.md
=> added Dave to contributors

.circleci/config.yml
so we know when something fails :-)
=> adding notifications for failed jobs for slack

terraform/variables.tf
=> bug fix dsp changes

README.md, ansible/roles/atomic_red_team/tasks/main.yml, ansible/roles/atomic_red_team/tasks/run_art_test.yml, ansible/roles/windows_universal_forwarder/files/atomic_red_team_execution_inputs.conf
=> bug fix ATC

.circleci/config.yml, attack_range.conf, demos/mission_control_demo-attack_range.conf
updating to adjust the new simulation code
=> updating attack technique to include the new sub-technique format

modules/CustomConfigParser.py
no special characters, spaces, single quotes allowed in key_name
=> updated the regex check

.circleci/config.yml, ansible/roles/atomic_red_team/tasks/install_art.yml, ansible/roles/atomic_red_team/tasks/main.yml, ansible/roles/atomic_red_team/tasks/run_art_test.yml, ansible/roles/sysmon/templates/SysmonConfig-TSwift2.xml.j2, ansible/roles/sysmon/templates/SysmonConfig.xml.j2, ansible/roles/windows_universal_forwarder/files/atomic_red_team_execution_inputs.conf, attack_range.conf, attack_range.py, modules/IEnvironmentController.py, modules/TerraformController.py, modules/aws_service.py, modules/splunk_sdk.py, tests/credential_dumping_lsass_memory_test.yml, tests/credential_dumping_ntds_test.yml, tests/credential_dumping_sam_test.yml
passed CI in ad-hoc execution https://app.circleci.com/pipelines/github/splunk/attack_range/287/workflows/e44b91fb-3f1e-47fe-9d19-1ff5e694499a/jobs/325
=> Fixing attack range ci

ansible/roles/sysmon/templates/AttackRangeSysmon.xml.j2, attack_range.conf, modules/TerraformController.py, modules/aws_service.py
Changes:
- Attack Data are stored compressed and uncompressed
- Changes to Sysmon Config for some detection testing
=> Improvements Attack Range

ansible/roles/atomic_red_team/tasks/main.yml, modules/VagrantController.py
=>  fix issue 301 missing args for art repo

modules/VagrantController.py
=> forcing virtualbox as provider

ansible/roles/linux_common/tasks/disable-dnssec.yml, ansible/roles/linux_common/tasks/main.yml, ansible/roles/linux_common/templates/disable-dnssec.conf.j2
Bettter fix for vagrant related DNS issues involving DNS sec configuration.
=> Disabling DNSSEC

ansible/roles/sysmon/tasks/windows-sysmon.yml, attack_range.conf
=> add sysmon to system PATH

ansible/roles/atomic_red_team/tasks/main.yml, ansible/roles/atomic_red_team/tasks/run_art_test.yml, ansible/roles/atomic_red_team/tasks/run_specific_atomics.yml, attack_range.conf, attack_range.py, modules/IEnvironmentController.py, modules/TerraformController.py, modules/VagrantController.py
changes:
- test file can have input variables, see: https://github.com/splunk/security-content/blob/TR-33_schtasks_scheduling_job_on_remote_system/tests/T1053_005.yml
- single atomics can be simulated with a new flag -sa
=> Input variables and simulation of atomics

vagrant/windows-domain-controller/Vagrantfile, vagrant/windows-server/Vagrantfile, vagrant/windows10/Vagrantfile
=> removed entry since it causes an error

README.md, attack_range.conf
since we removed vagrant mode a few things were out of date.
=> updating conf instructions

attack_range.conf
small bug in conf file, reseting
=> remove jose-ssh

attack_range.conf, terraform/modules/network/resources.tf
This should resolve issue https://github.com/splunk/attack_range/issues/335
=> Multiple cidr

ansible/roles/windows_universal_forwarder/files/win_event_log_inputs_plain.conf, ansible/roles/windows_universal_forwarder/tasks/collect_windows_event_logs.yml, attack_range.conf, terraform/modules/windows-domain-controller/resources.tf
Check this proposal.. don't know if you want to merge this in.
=> Added optional plain multiline to forward to Splunk

ansible/roles/windows_common/tasks/main.yml, ansible/roles/windows_common/tasks/windows-enable-4688-cmd-line-audit.yml, attack_range.conf, terraform/modules/windows-domain-controller/resources.tf
This commit allows logging command lines also in windows security events 4688.
=> Enabled command line for process creation on events 4688

attack_range.conf.template
=> removing caldera section since it is not needed

.circleci/config.yml, .gitignore, README.md, attack_range.conf.template, attack_range.py, modules/CustomConfigParser.py, modules/TerraformController.py, modules/aws_service.py, terraform/modules/kali_machine/resources.tf, terraform/modules/network/resources.tf, terraform/modules/phantom-server/resources.tf, terraform/modules/splunk-server/resources.tf, terraform/modules/windows-client/resources.tf, terraform/modules/windows-domain-controller/resources.tf, terraform/modules/windows-server/resources.tf, terraform/state/state.md
duplicate of PR multi-range-name with some small fixes
=> Jkuepker multi range name

ansible/playbooks/atomic_red_team.yml, ansible/roles/atomic_red_team/tasks/run_art_test.yml, ansible/roles/attack_data/tasks/main.yml, attack_data/dumps.yml, attack_range.conf.template, modules/TerraformController.py, modules/splunk_sdk.py
Changes:
- Added parameter to turn on/off dumping with json or evtx (dumping with search will be standard)
- encoding bug fix in dump command
- more dump.yml examples
- improved error handling for simulate command (analyse the return value to understand if attack was performe successfully)
=> Improve simulate cmd

modules/TerraformController.py
Verified that dumps have events ordered in chronological order
=> Dump in chronological order

README.md
=> minor readme edit, moving buidling to the top

attack_range.py
Small changes for Attack Data Project
=> small changes

.circleci/config.yml
Removed --action from circleci config with the new arg parsing
=> circleci fix removed --action

ansible/roles/atomic_red_team/tasks/run_specific_atomics.yml
=> small fix in simulate

modules/TerraformController.py, tests/T1003_002.yml
=> new test cmd

modules/TerraformController.py, tests/T1003_002.yml
=> change in test cmd

attack_range.conf.template, tests/T1003_001.yml
=> new_dashboard

modules/TerraformController.py, modules/splunk_sdk.py, tests/T1003_001.yml, tests/T1003_002.yml
=> improvements test cmd

ansible/roles/windows_common/tasks/set-hostname.yml, terraform/modules/network/resources.tf
too long hostname. reduced the random number
=> hostname was too long

README.md
fixing some minor broken links
=> fixing the broken links I found
